# Generated by Django 3.0.6 on 2020-05-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0002_user_staff_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_master',
        ),
        migrations.AddField(
            model_name='user',
            name='admin_status',
            field=models.BooleanField(default=True),
        ),
    ]
