# Generated by Django 3.0.6 on 2020-05-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0003_auto_20200528_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_picture',
            field=models.CharField(default='', max_length=300),
        ),
    ]
