# Generated by Django 3.0.6 on 2020-05-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0004_auto_20200528_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
