# Generated by Django 3.0.6 on 2020-06-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0007_auto_20200601_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff_status',
        ),
    ]
