# Generated by Django 3.0.6 on 2020-06-02 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0008_auto_20200601_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
