# Generated by Django 3.0.6 on 2020-06-02 14:21

from django.conf import settings
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0009_auto_20200602_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='project_member_related', related_query_name='project_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Testing', 'Testing'), ('Deployed', 'Deployed'), ('Production', 'Production'), ('Development', 'Development'), ('Scrapped', 'Scrapped'), ('Finished', 'Finished')], default='Testing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='wiki',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
