# Generated by Django 3.0.6 on 2020-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0014_auto_20200611_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='#775ada', max_length=10),
        ),
    ]
