# Generated by Django 3.0.6 on 2020-06-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0017_auto_20200613_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecticon',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='pesticide_app.Project'),
        ),
    ]
