# Generated by Django 3.0.6 on 2020-06-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0018_auto_20200618_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecticon',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj', to='pesticide_app.Project'),
        ),
    ]
