# Generated by Django 3.0.6 on 2020-07-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0021_auto_20200711_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pesticide_app.Tag'),
        ),
    ]
