# Generated by Django 3.0.6 on 2020-07-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0022_auto_20200711_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuestatus',
            name='issue_text',
            field=models.CharField(max_length=30),
        ),
    ]
