# Generated by Django 3.0.6 on 2020-07-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0023_auto_20200711_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuestatus',
            old_name='issue_text',
            new_name='status_text',
        ),
    ]
