# Generated by Django 3.0.6 on 2020-07-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0024_auto_20200711_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuestatus',
            name='type',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Closed'), ('3', 'Resolved')], default='1', max_length=2),
        ),
    ]
