# Generated by Django 3.0.6 on 2020-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0025_issuestatus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuestatus',
            name='type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='Pending', max_length=30),
        ),
    ]
