# Generated by Django 3.0.8 on 2020-07-31 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0027_auto_20200711_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
