# Generated by Django 3.0.8 on 2020-08-04 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0028_auto_20200731_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_new_project', models.BooleanField(blank=True, default=True, null=True)),
                ('on_project_membership', models.BooleanField(blank=True, default=True, null=True)),
                ('on_project_update', models.BooleanField(blank=True, default=True, null=True)),
                ('on_new_issue', models.BooleanField(blank=True, default=True, null=True)),
                ('on_issue_status_change', models.BooleanField(blank=True, default=True, null=True)),
                ('on_new_comment', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
