# Generated by Django 3.0.8 on 2020-08-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0029_emailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='on_issue_assign',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
