# Generated by Django 3.0.8 on 2020-08-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0030_emailsubscription_on_issue_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsubscription',
            name='on_project_update',
        ),
        migrations.AddField(
            model_name='emailsubscription',
            name='on_project_status_change',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
